<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
  <joint name="lidar_joint" type="fixed">
    <parent link="chassis"/>
    <child link="lidar"/>
    <origin xyz= "${chassis_length/2 + lidar_length/2} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="lidar">
     <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0"/>
      <material name="sunshine"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.05" radius="${lidar_radius}" length="${lidar_length}"/>
  </link>

  <gazebo reference="lidar">
    <material>Gazebo/Yellow</material>
    <sensor name="laser" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <sample>360</sample>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.05</min>
          <max>2</max>
        </range>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</robot>