<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
 

  <!-- BASE LINK -->

  <link name="base_link"></link>


  <!-- CHASSIS -->

  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="${chassis_length/2} 0 ${chassis_height/2 + wheel_radius}"/>
  </joint>

  <link name="chassis">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="2" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- LEFT WHEEL -->

  <joint name="base_link_to_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${-chassis_width/2} 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="sky_blue"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.5" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <gazebo reference="left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- RIGHT WHEEL -->

  <joint name="base_link_to_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${chassis_width/2} 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="sky_blue"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.5" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <gazebo reference="right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- FRONT PLATE -->

   <joint name="steering_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_plate"/>
    <origin xyz="${chassis_length} 0 ${front_plate_height/2 + wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="front_plate">
    <visual>
      <geometry>
        <cylinder radius="0.1" length="${front_plate_height}"/>
      </geometry>
      <origin xyz="0 0 0"/>
      <material name="rosy_red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.1" length="${front_plate_height}"/>
      </geometry>
      <origin xyz="0 0 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.1" radius="0.1" length="${front_plate_height}"/>
  </link>

  <gazebo reference="front_plate">
    <material>Gazebo/Red</material>
  </gazebo>


  <!-- FRONT WHEEL -->

  <joint name="traction_joint" type="continuous">
    <parent link="front_plate"/>
    <child link="front_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0 0 ${-front_plate_height/2 - wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="front_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0"/>
      <material name="sunshine"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.2" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <gazebo reference="front_wheel">
    <material>Gazebo/Yellow</material>
  </gazebo>

</robot>