<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
 

  <!-- BASE LINK -->

  <link name="base_link"></link>

  <!-- BASE FOOTPRINT -->

  <joint name="footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint"></link>


  <!-- CHASSIS -->

  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="${chassis_length/2} 0 ${chassis_height/2 + wheel_radius}"/>
  </joint>

  <link name="chassis">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.7" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/White</material>
  </gazebo>
  
  <!-- LEFT WHEEL -->

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="${chassis_length/3} ${chassis_width/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="sky_blue"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.2" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <gazebo reference="left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- RIGHT WHEEL -->
 
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="${chassis_length/3} ${-chassis_width/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="sky_blue"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.2" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <gazebo reference="right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- CASTER WHEEL -->
  
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${3*chassis_length/4} 0 ${wheel_radius}"/>
  </joint>

  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
      <material name="sunshine"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_sphere mass="0.1" radius="${wheel_radius}"/>
  </link>

  <gazebo reference="caster_wheel">
    <material>Gazebo/Yellow</material>
    <mu1 value="0.000"/>
    <mu2 value="0.000"/>
  </gazebo>

</robot>