import math

BLOCKED = 0
EMPTY = 254

PUBLISH_RATE = 0.1
ROBOT_COMFORT_RADIUS = 0.6
ROBOT_COVER_RADIUS = 0.3
ANGULAR_VELOCITY = math.pi/7
ANGULAR_PRECISION = 0.2
LINEAR_VELOCITY = 0.3
LINEAR_PRECISION = 0.05